### PR TITLE
Improves audio options

### PR DESCRIPTION
**Pull request by mschelstastic**
- adds additional "whileTyping" option for audioEnabled so that nyan cat can be always enabled while only playing music while typing.

### CODE REVIEW

**Comment by chriswa** [comment]
This is a business critical fix. Please approve.

**Comment by Aaronius** [comment]
Thanks! It sounds like a good idea. I've been busy traveling but I'll try to get to it soon. @chriswa, I hope your business can survive through this rough time.

**Comment by Aaronius** [comment]
Thanks for the contribution. I did a little more work on it to remove `alwaysActive` so we can just have `audioEnabled` and `videoEnabled` controlled separately. You'll want to check out the updated readme. I've released the changes in v4.0.0.

**Comment by mschelstastic** [comment]
awesome thanks so much! :D

This is literally the best plugin for Hyper ;)

**Pull request merged**
